version: '2'

services:
  mail_data:
    image: busybox
    volumes:
      - /var/mail           # Mail
      - /etc/mail           # DKIM Key
      - /etc/courier        # POP & IMAP Keys
      - /var/www/html/data  # Rainloop data
    mem_limit: 128m

  mail:
    build:
      context: .
    command: supervisord -n -c /etc/supervisor/supervisord.conf
    volumes_from:
      - mail_data
    volumes:
      - .:/host
    links:
      - mysql
    ports:
      - "25:25"
#      - "587:587"
#      - "110:110"
      - "143:143"
#      - "8080:80"
#      - "8443:443"
#      - "993:993"
#      - "465:465"
    mem_limit: 1024m
    env_file: env

  mysql:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: postfixadmin
      MYSQL_USER: postfixadmin
      MYSQL_PASSWORD: postfixpassword
    ports:
      - "3306:3306"

  roundcube:
    image: roundcube/roundcubemail:1.3.8-apache
    volumes:
      - "./config/roundcube:/var/www/html/config"
    links:
      - mysql
#    ports:
#      - "9080:80"
#      - "9443:443"
    environment:
      ROUNDCUBEMAIL_DB_TYPE: mysql
      ROUNDCUBEMAIL_DB_HOST: mysql
      ROUNDCUBEMAIL_DB_USER: root
      ROUNDCUBEMAIL_DB_PASSWORD: rootpassword
      ROUNDCUBEMAIL_DB_NAME: roundcubemail
      ROUNDCUBEMAIL_DEFAULT_HOST: mail
      ROUNDCUBEMAIL_DEFAULT_PORT: 143
      ROUNDCUBEMAIL_SMTP_SERVER: mail
      ROUNDCUBEMAIL_SMTP_PORT: 25
      ROUNDCUBEMAIL_BASEPATH: "/wm"

  nginx:
    build:
      context:
        ./nginx
    links:
      - mail
      - roundcube
    ports:
      - "80:80"
#      - "443:443"
   
