mail_data:
  image: busybox
  volumes:
  - /var/mail           # Mail
  - /etc/mail           # DKIM Key
  - /etc/courier        # POP & IMAP Keys
  - /var/www/html/data  # Rainloop data
  mem_limit: 128m

mail:
  image: jgrowl/mail
  command: supervisord -n -c /etc/supervisor/supervisord.conf
  volumes_from:
  - mail_data
  ports:
  - "25:25"
  - "587:587"
  - "110:110"
  - "143:143"
  - "80:80"
  - "993:993"
  - "465:465"
  mem_limit: 1024m
  env_file: env

#owncloud:
#  image: owncloud:8.1
#  volumes_from:
#  - mail_data
#  ports:
#  - "80:80"
#  mem_limit: 1024m
#  env_file: env
