---
# tasks file for jgrowl.configure_mail

- template: src=etc/apache2/conf-available/servername.conf.j2 dest=/etc/apache2/conf-available/servername.conf owner=root group=root mode=0600
- template: src=etc/courier/authdaemonrc.j2 dest=/etc/courier/authdaemonrc owner=root group=root mode=0600
- template: src=etc/courier/authmysqlrc.j2 dest=/etc/courier/authmysqlrc owner=root group=root mode=0600
- template: src=etc/default/opendkim.j2 dest=/etc/default/opendkim owner=root group=root mode=0600
- template: src=etc/default/saslauthd.j2 dest=/etc/default/saslauthd owner=root group=root mode=0600
- template: src=etc/pam.d/smtp.j2 dest=/etc/pam.d/smtp owner=root group=root mode=0600
- template: src=etc/postfix/sasl/smtpd.conf.j2 dest=/etc/postfix/sasl/smtpd.conf owner=root group=root mode=0600

- template: src=etc/postfix/main.cf.j2 dest=/etc/postfix/main.cf owner=root group=root mode=0640
- template: src=etc/postfix/mysql_relay_domains_maps.cf.j2 dest=/etc/postfix/mysql_relay_domains_maps.cf owner=root group=postfix mode=0640
- template: src=etc/postfix/mysql_virtual_alias_maps.cf.j2 dest=/etc/postfix/mysql_virtual_alias_maps.cf owner=root group=postfix mode=0640
- template: src=etc/postfix/mysql_virtual_domains_maps.cf.j2 dest=/etc/postfix/mysql_virtual_domains_maps.cf owner=root group=postfix mode=0640
- template: src=etc/postfix/mysql_virtual_mailbox_limit_maps.cf.j2 dest=/etc/postfix/mysql_virtual_mailbox_limit_maps.cf owner=root group=postfix mode=0640
- template: src=etc/postfix/mysql_virtual_mailbox_maps.cf.j2 dest=/etc/postfix/mysql_virtual_mailbox_maps.cf owner=root group=postfix mode=0640

- template: src=etc/rsyslog.d/rsyslogd.conf.j2 dest=/etc/rsyslog.d/rsyslogd.conf owner=root group=root mode=0600
- template: src=etc/supervisor/supervisord.conf.j2 dest=/etc/supervisor/supervisord.conf owner=root group=root mode=0600
- template: src=etc/opendkim.conf.j2 dest=/etc/opendkim.conf owner=root group=root mode=0600

- copy: src=generate-setup-password-hash.php dest=/usr/local/bin/generate-setup-password-hash.php mode=0755

- shell: /usr/local/bin/generate-setup-password-hash.php {{ configure_mail_postfixadmin_setup_password }}
  register: setup_password_hash

- template: src=usr/share/postfixadmin/config.inc.php.j2 dest=/usr/share/postfixadmin/config.inc.php owner=root group=root mode=0644

- command: opendkim-genkey -t -s {{ configure_mail_dkim_genkey_subdomain }} -d {{ configure_mail_dkim_genkey_domain }} && mv mail.private dkim.key creates=/etc/mail/dkim.key chdir=/etc/mail

- shell: cat /etc/mail/mail.txt
  register: dkim_txt_key

- debug: var=dkim_txt_key

- file: path=/var/mail state=directory recurse=yes mode=0755 owner=vmail group=vmail

- command: echo {{ configure_mail_mailname }} > /etc/mailname

#RUN sed -i -e 's@^mail.*@@g' /etc/rsyslog.conf

- command: mkpop3dcert && mv /usr/lib/courier/share/pop3d.pem . chdir=/etc/courier creates=/etc/courier/pop3d.pem

- command: mkimapdcert && mv /usr/lib/courier/share/imapd.pem chdir=/etc/courier creates=/etc/courier/imapd.pem

- name: Create global my.cnf
  template: src=etc/mysql/my.cnf.j2 dest=/etc/mysql/my.cnf

- name: Create local my.cnf for root user
  template: src=root/.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Restart the MySQL service
  action: service name=mysql state=restarted

- name: Add postfixadmin user and allow access to databases
  mysql_user: name={{ configure_mail_postfixadmin_database_user }} password={{ configure_mail_postfixadmin_database_password }} host="localhost" priv="{{ configure_mail_postfixadmin_database_name }}.*:ALL,GRANT" state=present

- name: Set root password
  mysql_user: name=root password={{ configure_mail_database_root_password }} host="{{ item }}" priv=*.*:ALL,GRANT state=present
  with_items:
  - 127.0.0.1
  - ::1
  - localhost
#  - "{{ansible_hostname}}"

- name: Enable override configurations
  command: a2enconf servername

